services:
    - type: web
      name: eclipse-angels-web
      runtime: static
      buildCommand: npx --yes pnpm@9 install && BASE_PATH=/ npx --yes pnpm@9 --filter @workspace/sirens-stream run build
      staticPublishPath: artifacts/sirens-stream/dist
      pullRequestPreviewsEnabled: false
      envVars:
        - key: VITE_API_URL
          value: https://eclipse-angels-web-api.onrender.com
        - key: VITE_SUPABASE_URL
          sync: false
        - key: VITE_SUPABASE_ANON_KEY
          sync: false
        - key: VITE_GROQ_API_KEY
          sync: false
      routes:
        - type: rewrite
          source: /*
          destination: /index.html

    - type: web
      name: eclipse-angels-api
      runtime: node
      buildCommand: npx --yes pnpm@9 install && npx --yes pnpm@9 --filter @workspace/api-server run build
      startCommand: npx --yes pnpm@9 --filter @workspace/api-server run start
      pullRequestPreviewsEnabled: false
      envVars:
        - key: NODE_ENV
          value: production
        - key: VAPID_PUBLIC_KEY
          value: BBdr3GZcSw_p6_54VakfGxtgou8XSB1mJBV0btx_aHxpXHI3FZsRaGPd6Fex1fvW7aplnZbCpFow0gdxskYk-S8
        - key: VAPID_PRIVATE_KEY
          value: G2M_CxsbU1KPAvffuoPq8Sd9rDxvdbcYFk8GPOjdfts
        - key: VAPID_SUBJECT
          value: mailto:eclipseangelsagency@gmail.com
        - key: GROQ_API_KEY
          sync: false
        - key: SUPABASE_URL
          sync: false
        - key: SUPABASE_SERVICE_ROLE_KEY
          sync: false
