import { Router, type IRouter } from 'express';
  import healthRouter from './health';
  import chatRouter from './chat';
  import statsRouter from './stats';
  import tutorialsRouter from './tutorials';
  import pushRouter from './push';
  import nominaStateRouter from './nomina-state';
  import agentCommissionsRouter from './agent-commissions';
  import publishRouter from './publish';
  import createAgentRouter from './create-agent';
  import agentWorkersRouter from './agent-workers';
  import cierreSemanalRouter from './cierre-semanal';
  import coliderRouter from './colider';
  import siteSettingsRouter from './site-settings';
  import channelsRouter from './channels';
  import profileRouter from './profile';
  import agentCommissionsAdminRouter from './agent-commissions-admin';
  import customWorkerRatesRouter from './custom-worker-rates';
  import rankingRouter from './ranking';
  import workerEntriesRouter from './worker-entries';
  import inAppNotificationsRouter from './in-app-notifications';
  import telegramRouter from './telegram';
import adminPaidMarksRouter from './admin-paid-marks';
import paymentConfirmationsRouter from './payment-confirmations';
import adminPagosRouter from './admin-pagos';
import paymentMethodLockRouter from './payment-method-lock';
  import adminUsersRouter from './admin-users';

  const router: IRouter = Router();

  router.use(healthRouter);
  router.use(chatRouter);
  router.use(statsRouter);
  router.use(tutorialsRouter);
  router.use(pushRouter);
  router.use(nominaStateRouter);
  router.use(agentCommissionsRouter);
  router.use(publishRouter);
  router.use(createAgentRouter);
  router.use(agentWorkersRouter);
  router.use(cierreSemanalRouter);
  router.use(coliderRouter);
  router.use(siteSettingsRouter);
  router.use(channelsRouter);
  router.use(profileRouter);
  router.use(agentCommissionsAdminRouter);
  router.use(customWorkerRatesRouter);
  router.use(rankingRouter);
  router.use(workerEntriesRouter);
  router.use(inAppNotificationsRouter);
  router.use(telegramRouter);
  router.use(adminPaidMarksRouter);
  router.use(paymentConfirmationsRouter);
  router.use(adminPagosRouter);
  router.use(paymentMethodLockRouter);
    router.use(adminUsersRouter);

  export default router;
  